//* ======================================= База данных страницы "Игра" ========================================*\\

import { IlistGallery } from './IdataGamePage'

export const listGallery: IlistGallery[] = [
	{
		id: 'slide-1',
		width: 988,
		height: 555,
		widthThumbs: 101,
		heightThumbs: 58,
		img: 'assets/img/game-page/gallery/1_a66_m103_redshir_1024x.jpg',
		imgWebP: 'assets/img/game-page/gallery/1_a66_m103_redshir_1024x.webp',
		imgThumbs: 'assets/img/game-page/gallery/thumbs/1_a66_m103_redshir_103x.jpg',
		imgThumbsWebP: 'assets/img/game-page/gallery/thumbs/1_a66_m103_redshir_103x.webp',
		type: 'image/webp',
		alt: 'Изображение',
		altThumbs: 'Миниатюра',
	},
	{
		id: 'slide-2',
		width: 988,
		height: 555,
		widthThumbs: 101,
		heightThumbs: 58,
		img: 'assets/img/game-page/gallery/2_j25_type_4_himmelsdorf_1024x.jpg',
		imgWebP: 'assets/img/game-page/gallery/2_j25_type_4_himmelsdorf_1024x.webp',
		imgThumbs: 'assets/img/game-page/gallery/thumbs/2_j25_type_4_himmelsdorf_103x.jpg',
		imgThumbsWebP: 'assets/img/game-page/gallery/thumbs/2_j25_type_4_himmelsdorf_103x.webp',
		type: 'image/webp',
		alt: 'Изображение',
		altThumbs: 'Миниатюра',
	},
	{
		id: 'slide-3',
		width: 988,
		height: 555,
		widthThumbs: 101,
		heightThumbs: 58,
		img: 'assets/img/game-page/gallery/3_f18_bat_chatillon25t_pereval_1024x.jpg',
		imgWebP: 'assets/img/game-page/gallery/3_f18_bat_chatillon25t_pereval_1024x.webp',
		imgThumbs: 'assets/img/game-page/gallery/thumbs/3_f18_bat_chatillon25t_pereval_103x.jpg',
		imgThumbsWebP: 'assets/img/game-page/gallery/thumbs/3_f18_bat_chatillon25t_pereval_103x.webp',
		type: 'image/webp',
		alt: 'Изображение',
		altThumbs: 'Миниатюра',
	},
	{
		id: 'slide-4',
		width: 988,
		height: 555,
		widthThumbs: 101,
		heightThumbs: 58,
		img: 'assets/img/game-page/gallery/4_r45_is_7_mannerheim_line_1024x.jpg',
		imgWebP: 'assets/img/game-page/gallery/4_r45_is_7_mannerheim_line_1024x.webp',
		imgThumbs: 'assets/img/game-page/gallery/thumbs/4_r45_is_7_mannerheim_line_103x.jpg',
		imgThumbsWebP: 'assets/img/game-page/gallery/thumbs/4_r45_is_7_mannerheim_line_103x.webp',
		type: 'image/webp',
		alt: 'Изображение',
		altThumbs: 'Миниатюра',
	},
	{
		id: 'slide-5',
		width: 988,
		height: 555,
		widthThumbs: 101,
		heightThumbs: 58,
		img: 'assets/img/game-page/gallery/5_a116_xm551_prohorovka_1024x.jpg',
		imgWebP: 'assets/img/game-page/gallery/5_a116_xm551_prohorovka_1024x.webp',
		imgThumbs: 'assets/img/game-page/gallery/thumbs/5_a116_xm551_prohorovka_103x.jpg',
		imgThumbsWebP: 'assets/img/game-page/gallery/thumbs/5_a116_xm551_prohorovka_103x.webp',
		type: 'image/webp',
		alt: 'Изображение',
		altThumbs: 'Миниатюра',
	},
	{
		id: 'slide-6',
		width: 988,
		height: 555,
		widthThumbs: 101,
		heightThumbs: 58,
		img: 'assets/img/game-page/gallery/6_a120_m48a5_patton_aerodrom_1024x.jpg',
		imgWebP: 'assets/img/game-page/gallery/6_a120_m48a5_patton_aerodrom_1024x.webp',
		imgThumbs: 'assets/img/game-page/gallery/thumbs/6_a120_m48a5_patton_aerodrom_103x.jpg',
		imgThumbsWebP: 'assets/img/game-page/gallery/thumbs/6_a120_m48a5_patton_aerodrom_103x.webp',
		type: 'image/webp',
		alt: 'Изображение',
		altThumbs: 'Миниатюра',
	},
	{
		id: 'slide-7',
		width: 988,
		height: 555,
		widthThumbs: 101,
		heightThumbs: 58,
		img: 'assets/img/game-page/gallery/7_a116_xm551_mannerheim_line_1024x.jpg',
		imgWebP: 'assets/img/game-page/gallery/7_a116_xm551_mannerheim_line_1024x.webp',
		imgThumbs: 'assets/img/game-page/gallery/thumbs/7_a116_xm551_mannerheim_line_103x.jpg',
		imgThumbsWebP: 'assets/img/game-page/gallery/thumbs/7_a116_xm551_mannerheim_line_103x.webp',
		type: 'image/webp',
		alt: 'Изображение',
		altThumbs: 'Миниатюра',
	},
	{
		id: 'slide-8',
		width: 988,
		height: 555,
		widthThumbs: 101,
		heightThumbs: 58,
		img: 'assets/img/game-page/gallery/8_lt08_progetto_m40_mod_65_el-halluf_1024x.jpg',
		imgWebP: 'assets/img/game-page/gallery/8_lt08_progetto_m40_mod_65_el-halluf_1024x.webp',
		imgThumbs: 'assets/img/game-page/gallery/thumbs/8_lt08_progetto_m40_mod_65_el-halluf_103x.jpg',
		imgThumbsWebP: 'assets/img/game-page/gallery/thumbs/8_lt08_progetto_m40_mod_65_el-halluf_103x.webp',
		type: 'image/webp',
		alt: 'Изображение',
		altThumbs: 'Миниатюра',
	},
	{
		id: 'slide-9',
		width: 988,
		height: 555,
		widthThumbs: 101,
		heightThumbs: 58,
		img: 'assets/img/game-page/gallery/9_r133_kv_122_02_murovanka_1024x.jpg',
		imgWebP: 'assets/img/game-page/gallery/9_r133_kv_122_02_murovanka_1024x.webp',
		imgThumbs: 'assets/img/game-page/gallery/thumbs/9_r133_kv_122_02_murovanka_103x.jpg',
		imgThumbsWebP: 'assets/img/game-page/gallery/thumbs/9_r133_kv_122_02_murovanka_103x.webp',
		type: 'image/webp',
		alt: 'Изображение',
		altThumbs: 'Миниатюра',
	},
	{
		id: 'slide-10',
		width: 988,
		height: 555,
		widthThumbs: 101,
		heightThumbs: 58,
		img: 'assets/img/game-page/gallery/10_gb31_conqueror_gc_rudniki_1024x.jpg',
		imgWebP: 'assets/img/game-page/gallery/10_gb31_conqueror_gc_rudniki_1024x.webp',
		imgThumbs: 'assets/img/game-page/gallery/thumbs/10_gb31_conqueror_gc_rudniki_103x.jpg',
		imgThumbsWebP: 'assets/img/game-page/gallery/thumbs/10_gb31_conqueror_gc_rudniki_103x.webp',
		type: 'image/webp',
		alt: 'Изображение',
		altThumbs: 'Миниатюра',
	},
]




